// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfTmKrEdhVyQqR0bugn9LWgGjhuBxf0Q',
    appId: '1:212206116447:web:69ad9814930b07bf0945ea',
    messagingSenderId: '212206116447',
    projectId: 'flutter-work-61112',
    authDomain: 'flutter-work-61112.firebaseapp.com',
    storageBucket: 'flutter-work-61112.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrmo56fPjbq9Hgozrhvm7zFbp0WrLof_w',
    appId: '1:212206116447:android:c8e7715dcf60f70b0945ea',
    messagingSenderId: '212206116447',
    projectId: 'flutter-work-61112',
    storageBucket: 'flutter-work-61112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZxpeEymm4a3WNU6-fmK57ETNurkH59s',
    appId: '1:212206116447:ios:6534715a309da8e60945ea',
    messagingSenderId: '212206116447',
    projectId: 'flutter-work-61112',
    storageBucket: 'flutter-work-61112.appspot.com',
    iosBundleId: 'com.sahyog.remoteWorkCollaboration',
  );
}
